name: Publish docs on GitHub Pages
on:
  push:
    branches:
      - master
jobs:
  build:
    name: Deploy docs
    runs-on: ubuntu-latest
    steps:
      - name: Checkout master
        uses: actions/checkout@v2
      - name: Setup Python 3
        uses: actions/setup-python@v2
        with:
          python-version: 3.x
      - name: Cache some files
        uses: actions/cache@v2
        with:
          key: ${{ github.ref }}
          path: .cache
      - name: Install mkdocs and plugins
        run: pip install -r requirements.txt
      - name: Build and deploy
        run: mkdocs gh-deploy --force
